name: Build

on:
  push:
    branches:
      - main

jobs:
  run-tests-and-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install wrench-daemon
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          docker pull wrenchproject/wrench:unstable
      - name: Start wrench-daemon
        run: |
          docker run --name wrench-daemon-container -v `pwd`:/home/wrench wrenchproject/wrench:unstable wrench-daemon &
      - name: Install the wrench Python API
        run: |
          docker exec --workdir /home/wrench/ wrench-daemon-container sudo pip install .
      - name: Run all tests
        run: |
          docker exec --workdir /home/wrench/tests bash ./run_all_tests.sh
      - name: Run all examples
        run: |
          docker exec --workdir /home/wrench/examples bash ./run_all_tests.sh
      - name: Kill wrench-daemon
        run: |
          docker kill wrench-daemon-container
  build-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-sphinx sphinx-rtd-theme-common
          pip install sphinx-rtd-theme
          pip install sphinx_rtd_theme recommonmark
      - name: Check package install
        run: |
          pip install .
      - name: Build documentation
        run: |
          cd docs
          make html
